model:
  name: "mistralai/Mistral-7B-Instruct-v0.3"
  type: "mistral"
  temperature: 0.6
  top_p: 0.9
  top_k: 40
  max_length: 4096
  max_tokens: 512
  tokenizer_kwargs:
    trust_remote_code: true
  model_kwargs:
    trust_remote_code: true
    dtype: "bfloat16"

inference:
  outgoing_speaker_name: "Ryan Amiri"
  model_request_timeout: 120.0
  debounce_seconds: 2.5
